### ISSUE TITLE
Team/Dragon

### ISSUE THREAD

**Issue by Claptar** [Claptar/Dream-team#4]

**Comment by Claptar** [comment]
@antosha417
ffce4ebe426ae4f643cf878c515c05fd1c4b27d1
a8d9672a05e146a283c48d7b5efce7fa364cb4fd
b34799b195ad53239ebdf93aa9d9f637666b9b72
daaec8d6391682dfe5f2cec6dd2d252d84f5985d
c4eec459b3f2de8533ff5cbeccbe6a22cc88c725
b39aa8f32f7d5f69525075e90622d1179a42f5a9
5fe553cbfeb5e288b378ae2f133252e6ae515876
612a22794132a7f8f6e54b9f5ddc4ecf442b7386
06e1c24fff543228882ff1a2390bcbc2978a9dcf
7694c72e65c415c5ecfea99174fb501c2740973c
09ce7acd058cd00d5ab007d62136404424f71e83
76c59ffccb4fb9e9c37dc8c229138c88cd608ffb
ff64576b1fd7fd61fba5cbd8d720c83f261ce264
18c9ff690a370024726977f56374e504d8618ab8
030857fbe56bd79094f2de792bb7259b24603bca
68a859f39ac995be580fb0c37bf4a1d4831ad589
10f9e39ab093fb6f33e5da0562a564fd417a9995
e654f74213be3150e450bbaa6eddadb5a9fc9be0
bab9c226a37b9de8e71553c91b69c483da993331
Мне же по идее не нужно было столько коммитов присоединять, да ?) В следующий раз загружать только основные обновления master, да ?

**Comment by Claptar** [comment]
Ветки:
 Алесь - Алесь (main, hero, gameunit)
Миша - Misha (tournament)
Настя - Enemies (enemies)

**Comment by antosha417** [comment]
Я посмотрю коммиты сам в групповых проектах, их всё же в 3 раза меньше, значит на проверку у меня в 3 раза больше времени и проверять могу качественней.

**Comment by antosha417** [comment]
Хорошо, что вы просматриваете коммиты друг друга и пишите коментарии.
Хорошо пишете сообщения к коммитам.
Плохо, что кто-то пушит в мастер! Делайте отдельную векту, в мастер только мердж делайте
